/**
 * Read inbound mail from Gmail over IMAP.
 *
 * ---------------------------------------------------------------------------
 * PHASE 1 ONLY — App Password on a mailbox we control.
 *
 * This is deliberately the simple path: an App Password needs no Google Cloud
 * project, no consent screen, and no verification review, which makes it right
 * for development against our own test mailbox.
 *
 * It is NOT right for customer mailboxes, and must not ship that way. An App
 * Password grants full read AND send access to the whole account, cannot be
 * scoped to "read the COI inbox", and cannot be revoked per-integration —
 * revoking it breaks every other thing using it. Production connects each
 * agency's mailbox with per-tenant OAuth, where the grant is scoped to
 * gmail.readonly and the agency can withdraw it without touching anything else.
 *
 * The seam is this file: `fetchRecent` returns plain objects, so swapping the
 * transport later leaves ingestion and interpretation untouched.
 * ---------------------------------------------------------------------------
 *
 * READ-ONLY BY CONSTRUCTION: the mailbox is opened with `readOnly: true`, so
 * polling cannot mark messages seen, move them, or delete them. Whatever else
 * goes wrong, we cannot damage the customer's mailbox. De-duplication is the
 * database's job — `coi_requests_msg_uq` on (tenant, gmailMessageId) — rather
 * than the \Seen flag, which keeps this side effect-free.
 */

import { ImapFlow } from "imapflow";
import { simpleParser } from "mailparser";
import { AUTO_HEADER } from "./send";

export interface InboundEmail {
  /** RFC 822 Message-ID. Stable across fetches — our de-duplication key. */
  messageId: string;
  threadId: string | null;
  /**
   * Message-IDs this email is answering, ours first.
   *
   * How a reply is tied back to the request that prompted it. Gmail's thread id
   * would often do the same job, but these headers are standard, survive
   * forwarding between providers, and are what we set when we asked the
   * question in the first place.
   */
  inReplyTo: string[];
  /**
   * True when this is mail the system itself sent.
   *
   * The mailbox we read is also the mailbox we reply from, so our own output
   * comes straight back. A clarification question says "certificate of
   * insurance" throughout and would otherwise be classified as a request, and
   * it references the very message it is asking about — so it would also look
   * like the answer to itself.
   */
  autoGenerated: boolean;
  fromAddr: string;
  fromName: string | null;
  subject: string | null;
  /** Plain-text body. HTML-only mail is converted; never null. */
  body: string;
  receivedAt: Date;
}

export interface GmailConfig {
  /** Login name for IMAP and SMTP. */
  user: string;
  appPassword: string;
  /** IMAP host/port. */
  host?: string;
  port?: number;
  mailbox?: string;
  /** SMTP host/port for replies. Defaults to Gmail's, as before. */
  smtpHost?: string;
  smtpPort?: number;
  /** The address replies are sent From. Defaults to `user`. */
  fromAddress?: string;
  /** Set for an agency's own mailbox: hosts are re-checked against lib/mail/netguard.ts. */
  tenantConfigured?: boolean;
  /**
   * Present when the inbox was connected by OAuth (Google / Microsoft). Then
   * there is no password or host at all: mail moves over the provider's API
   * (lib/mail/api.ts) with a short-lived token.
   */
  oauth?: { tenantId: string; provider: "google" | "microsoft" };
}

export function gmailConfigFromEnv(): GmailConfig {
  const user = process.env.GMAIL_USER;
  const appPassword = process.env.GMAIL_APP_PASSWORD;
  if (!user || !appPassword) {
    throw new Error(
      "GMAIL_USER and GMAIL_APP_PASSWORD must be set in .env.local. " +
        "Generate an App Password at https://myaccount.google.com/apppasswords " +
        "(requires 2-Step Verification on that account)."
    );
  }
  return {
    user,
    // Google displays App Passwords in four groups for readability; IMAP wants
    // the bare 16 characters.
    appPassword: appPassword.replace(/\s+/g, ""),
    host: process.env.GMAIL_IMAP_HOST ?? "imap.gmail.com",
    port: Number(process.env.GMAIL_IMAP_PORT ?? 993),
    mailbox: process.env.GMAIL_MAILBOX ?? "INBOX",
    smtpHost: process.env.GMAIL_SMTP_HOST ?? "smtp.gmail.com",
    smtpPort: Number(process.env.GMAIL_SMTP_PORT ?? 465),
  };
}

/**
 * One raw RFC 822 message -> InboundEmail. Shared by every transport (IMAP,
 * Gmail API, Microsoft Graph), so whatever the mailbox, ingestion sees the
 * same shape parsed the same way. Null when there is no sender to reply to.
 */
export async function parseRawEmail(
  source: Buffer | string,
  meta: { fallbackId: string; threadId: string | null; receivedAt?: Date | string }
): Promise<InboundEmail | null> {
  const parsed = await simpleParser(source);
  const from = parsed.from?.value?.[0];
  if (!from?.address) return null; // no sender we can reply to
  return {
    messageId: parsed.messageId ?? meta.fallbackId,
    threadId: meta.threadId,
    inReplyTo: referencedIds(parsed),
    autoGenerated: Boolean(parsed.headers?.get?.(AUTO_HEADER.toLowerCase())),
    fromAddr: from.address.toLowerCase(),
    fromName: from.name || null,
    subject: parsed.subject ?? null,
    body: bodyText(parsed),
    // internalDate is typed loosely by the library and can arrive as a
    // string; normalise so callers always get a real Date.
    receivedAt: parsed.date ?? toDate(meta.receivedAt),
  };
}

/** Prefer text/plain; fall back to stripping the HTML part. */
function bodyText(parsed: { text?: string; html?: string | false }): string {
  if (parsed.text?.trim()) return parsed.text;
  const html = typeof parsed.html === "string" ? parsed.html : "";
  return html
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/p>/gi, "\n\n")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/[ \t]+/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

/**
 * Every Message-ID this email answers, in-reply-to first.
 *
 * EXPORTED FOR TESTING. Getting this wrong is silent and expensive: a reply the
 * system cannot tie back to its request is ingested as a NEW request instead,
 * which then looks ambiguous all over again and triggers a second question to
 * somebody who has already answered.
 *
 * mailparser types these loosely — either header can arrive as a single string
 * or an array, and either can be missing — so they are normalised here rather
 * than at each call site.
 */
export function referencedIds(parsed: { inReplyTo?: string; references?: string | string[] }): string[] {
  const raw: string[] = [];
  if (parsed.inReplyTo) raw.push(parsed.inReplyTo);
  if (Array.isArray(parsed.references)) raw.push(...parsed.references);
  else if (parsed.references) raw.push(parsed.references);

  const ids: string[] = [];
  for (const entry of raw) {
    for (const id of entry.split(/\s+/)) {
      const trimmed = id.trim();
      if (trimmed) ids.push(trimmed);
    }
  }
  return [...new Set(ids)];
}

function toDate(value: Date | string | undefined): Date {
  if (value instanceof Date) return value;
  if (typeof value === "string") {
    const parsed = new Date(value);
    if (!Number.isNaN(parsed.getTime())) return parsed;
  }
  return new Date();
}

export interface FetchOptions {
  /** Only messages newer than this. Defaults to the last 30 days. */
  since?: Date;
  /** Hard cap, newest first. Defaults to 25. */
  limit?: number;
  /**
   * Only messages with a UID above this.
   *
   * The difference between a fast poll and a slow one. Without it every check
   * downloads and parses the whole recent window to discover that it has seen
   * all of it already — tens of messages, several seconds, many times a minute.
   * With it, a check that finds nothing costs one search and no downloads.
   *
   * UIDs are only meaningful within one `uidValidity`; the caller must discard
   * a stored UID when that changes. See `fetchMailbox`.
   */
  sinceUid?: number;
  /**
   * An already-connected client to use instead of opening a new one.
   *
   * The mailbox watcher holds a connection open anyway; letting the fetch ride
   * on it removes a handshake and a login from the critical path. Ownership is
   * NOT transferred — a borrowed connection is never logged out here.
   */
  client?: ImapFlow;
}

export interface FetchResult {
  emails: InboundEmail[];
  /** Identifies the UID sequence. If this changes, stored UIDs are worthless. */
  uidValidity: string;
  /** Highest UID seen, for the next incremental fetch. 0 when none. */
  highestUid: number;
}

/**
 * Fetch recent messages. Never mutates the mailbox.
 *
 * Returns newest first so a low `limit` gets the most relevant mail rather than
 * whatever happens to be oldest.
 */
export async function fetchRecent(
  config: GmailConfig,
  options: FetchOptions = {}
): Promise<InboundEmail[]> {
  return (await fetchMailbox(config, options)).emails;
}

/**
 * Fetch, reporting enough for the caller to make the next fetch incremental.
 *
 * Supply `sinceUid` from a previous result and only messages above it are
 * downloaded. Compare the returned `uidValidity` with the one you stored: if it
 * differs, the server has renumbered the mailbox and any UID you kept means
 * nothing — discard it and fetch by date instead.
 */
export async function fetchMailbox(
  config: GmailConfig,
  options: FetchOptions = {}
): Promise<FetchResult> {
  // OAuth-connected inboxes are read over the provider's API, not IMAP.
  if (config.oauth) {
    const { fetchViaApi } = await import("@/lib/mail/api");
    return fetchViaApi(config, options);
  }

  const since = options.since ?? new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
  const limit = options.limit ?? 25;

  // Borrow a connection that is already open and authenticated when one is
  // offered. Establishing a fresh one costs a TLS handshake and a login —
  // one to two seconds against Gmail — which is most of the delay between a
  // message landing and the reviewer seeing it, and all of the variance.
  const borrowed = options.client && options.client.usable ? options.client : null;

  const client =
    borrowed ??
    new ImapFlow({
      host: config.host ?? "imap.gmail.com",
      port: config.port ?? 993,
      secure: true,
      auth: { user: config.user, pass: config.appPassword },
      // The library logs the full IMAP conversation at info level, which on a
      // failed login includes the credential. Errors only.
      logger: false,
    });

  const emails: InboundEmail[] = [];
  let uidValidity = "";
  let highestUid = 0;

  if (!borrowed) await client.connect();
  try {
    // readOnly: opens with EXAMINE rather than SELECT — the server itself
    // refuses any flag change, so this cannot mark mail as read.
    const lock = await client.getMailboxLock(config.mailbox ?? "INBOX", { readOnly: true });
    try {
      const box = client.mailbox;
      uidValidity = box && typeof box !== "boolean" ? String(box.uidValidity ?? "") : "";

      // Ask for as little as possible. `sinceUid` turns a check that finds
      // nothing into one search and zero downloads, which is what makes
      // checking every few seconds affordable.
      const uids = options.sinceUid
        ? await client.search({ uid: `${options.sinceUid + 1}:*` }, { uid: true })
        : await client.search({ since }, { uid: true });

      // `n:*` always matches at least the last message even when nothing is
      // newer, so anything at or below the watermark is filtered out here.
      const found: number[] = Array.isArray(uids) ? uids : [];
      const fresh = found.filter((uid) => !options.sinceUid || uid > options.sinceUid);
      if (!fresh.length) {
        return { emails: [], uidValidity, highestUid: options.sinceUid ?? 0 };
      }

      const newest = fresh.slice(-limit).reverse();

      for await (const message of client.fetch(
        newest,
        { uid: true, source: true, internalDate: true, threadId: true },
        { uid: true }
      )) {
        if (message.uid > highestUid) highestUid = message.uid;
        if (!message.source) continue;
        const email = await parseRawEmail(message.source, {
          fallbackId: `uid-${message.uid}@${config.user}`,
          threadId: (message as { threadId?: string }).threadId ?? null,
          receivedAt: message.internalDate,
        });
        if (email) emails.push(email);
      }
    } finally {
      lock.release();
    }
  } finally {
    // Only close what we opened. Logging out a borrowed connection would kill
    // the watcher that lent it.
    if (!borrowed) await client.logout().catch(() => client.close());
  }

  return { emails, uidValidity, highestUid: Math.max(highestUid, options.sinceUid ?? 0) };
}
