/**
 * Send mail through Gmail over SMTP, as a reply in the original thread.
 *
 * Threading is not cosmetic. A certificate that lands as a new, unrelated
 * message forces the requester to match it up by hand, and in a shared
 * compliance inbox it often gets missed entirely. Replying in-thread puts the
 * document directly under the request that asked for it.
 *
 * Three headers do that work, and all three are required — mail clients differ
 * in which they honour:
 *   In-Reply-To:  the Message-ID of the message being answered
 *   References:   the thread's chain, ending with that Message-ID
 *   Subject:      "Re: <original subject>"
 *
 * Phase 1 uses the same App Password as ingestion. Production sends per-tenant
 * OAuth from the agency's own domain, so replies come from an address the
 * requester recognises; the seam is this file.
 */

import nodemailer from "nodemailer";
import { gmailConfigFromEnv } from "./inbox";
import { guardConfig, mailConfigFor } from "@/lib/mail/settings";

export interface Attachment {
  filename: string;
  content: Buffer;
  contentType: string;
}

export interface ReplyMessage {
  /**
   * The agency sending. Its own mailbox is used, so the reply comes from the
   * address the requester wrote to. Omitted only by the dev/test scripts,
   * which send from the .env mailbox.
   */
  tenantId?: string;
  to: string;
  subject: string;
  text: string;
  /** RFC 822 Message-ID of the email being replied to. Enables threading. */
  inReplyTo?: string | null;
  /** The request's provider thread id, so an OAuth (Gmail API) reply files under it. */
  threadId?: string | null;
  attachments?: Attachment[];
  /**
   * Extra headers.
   *
   * Used to stamp mail the system generated by itself, so that ingestion can
   * recognise its own output. Without it, a clarification sent to a mailbox we
   * also read comes straight back in, gets classified as a certificate request
   * because it says "certificate of insurance" throughout, and the system ends
   * up answering itself.
   */
  headers?: Record<string, string>;
}

/** Stamped on every message the system sends without a human. */
export const AUTO_HEADER = "X-CertFlow-Auto";

export interface SentMessage {
  messageId: string;
  accepted: string[];
  rejected: string[];
}

export class DeliveryBlocked extends Error {
  constructor(message: string) {
    super(message);
    this.name = "DeliveryBlocked";
  }
}

/**
 * Who we are permitted to email.
 *
 * DELIVERY_ALLOWLIST is a comma-separated list of exact addresses, @domains, or
 * the single entry `*` meaning "any real address". It is the only lever:
 *
 *   unset, outside production   only GMAIL_USER   (safe default)
 *   unset, production           anyone            (real holders, real addresses)
 *   "*"                         anyone
 *   "a@b.com,@partner.com"      exactly those
 *
 * The default outside production is narrow on purpose: development runs against
 * a real SMTP account and a database full of test data, which is exactly the
 * situation where a stray click emails a stranger. Widening it is a deliberate
 * edit to .env.local, not something the app can decide for itself.
 *
 * The reserved-domain check below is NOT part of the allowlist, and `*` does
 * not lift it. That check is what stops seeded demo data reaching a mailbox,
 * and it costs nothing real — no genuine requester has a .example address.
 */
export function assertDeliverable(to: string, ownMailbox?: string): void {
  const address = to.trim().toLowerCase();

  if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(address)) {
    throw new DeliveryBlocked(`"${to}" is not a valid email address.`);
  }

  // Reserved by IANA precisely so it can never be delivered. Our seed data uses
  // it, so this is the check that catches "someone pressed Send on the demo".
  if (/\.(example|invalid|test|localhost)$/.test(address.split("@")[1] ?? "")) {
    throw new DeliveryBlocked(
      `"${to}" uses a reserved domain and cannot receive mail. This is seeded demo data — ` +
        `send a real request to the mailbox and try again.`
    );
  }

  const raw = process.env.DELIVERY_ALLOWLIST?.trim();
  const production = process.env.NODE_ENV === "production";

  if (!raw) {
    if (production) return; // real holders, real addresses
    const owner = (ownMailbox ?? process.env.GMAIL_USER)?.trim().toLowerCase();
    if (owner && address === owner) return;
    throw new DeliveryBlocked(
      `Refusing to email ${to}: outside production, delivery is limited to the ` +
        `configured mailbox (${owner ?? "GMAIL_USER"}). Set DELIVERY_ALLOWLIST=* in ` +
        `.env.local to reply to whatever address a request came from, or list ` +
        `specific addresses and @domains.`
    );
  }

  const allowed = raw
    .split(",")
    .map((entry) => entry.trim().toLowerCase())
    .filter(Boolean);

  // `*` — reply to whoever wrote in. The requester's address is not ours to
  // predict, so an agency taking real requests has to run this way.
  if (allowed.includes("*")) return;

  const ok = allowed.some((entry) =>
    entry.startsWith("@") ? address.endsWith(entry) : address === entry
  );
  if (!ok) {
    throw new DeliveryBlocked(`Refusing to email ${to}: not in DELIVERY_ALLOWLIST.`);
  }
}

/** Wrap a bare Message-ID in angle brackets, as the RFC requires. */
function bracket(id: string): string {
  const trimmed = id.trim();
  return trimmed.startsWith("<") ? trimmed : `<${trimmed}>`;
}

export async function sendReply(message: ReplyMessage): Promise<SentMessage> {
  const config = message.tenantId ? await mailConfigFor(message.tenantId) : gmailConfigFromEnv();
  const from = config.fromAddress ?? config.user;
  assertDeliverable(message.to, from);

  // An empty message is always a bug upstream, never an intention. Sending it
  // anyway spends the recipient's attention on nothing and, worse, makes the
  // fault look like a mail problem rather than the composition problem it is.
  // Refusing here turns a silent empty send into a traceable error.
  if (!message.text?.trim() && !message.attachments?.length) {
    throw new DeliveryBlocked(
      `Refusing to send an empty message to ${message.to} (subject: "${message.subject}").`
    );
  }

  // OAuth inbox: send through the provider's API as the connected account.
  if (config.oauth) {
    const { sendViaApi } = await import("@/lib/mail/api");
    const inReplyTo = message.inReplyTo ? bracket(message.inReplyTo) : undefined;
    const sent = await sendViaApi(config, {
      from,
      to: message.to,
      subject: /^re:/i.test(message.subject) ? message.subject : `Re: ${message.subject}`,
      text: message.text,
      inReplyTo,
      references: inReplyTo ? [inReplyTo] : undefined,
      headers: message.headers,
      attachments: message.attachments,
      threadId: message.threadId,
    });
    return { messageId: sent.messageId, accepted: [message.to], rejected: [] };
  }

  await guardConfig(config);

  const port = config.smtpPort ?? Number(process.env.GMAIL_SMTP_PORT ?? 465);
  const transport = nodemailer.createTransport({
    host: config.smtpHost ?? process.env.GMAIL_SMTP_HOST ?? "smtp.gmail.com",
    port,
    // 465 is TLS from the first byte; 587 upgrades with STARTTLS, which is
    // REQUIRED rather than attempted, so a downgrade cannot send in the clear.
    secure: port === 465,
    requireTLS: true,
    auth: { user: config.user, pass: config.appPassword },
  });

  try {
    const inReplyTo = message.inReplyTo ? bracket(message.inReplyTo) : undefined;

    const info = await transport.sendMail({
      from,
      to: message.to,
      // "Re:" is not what threads the message — the headers below are — but
      // clients that group by subject need it, and humans expect it.
      subject: /^re:/i.test(message.subject) ? message.subject : `Re: ${message.subject}`,
      text: message.text,
      inReplyTo,
      references: inReplyTo ? [inReplyTo] : undefined,
      attachments: message.attachments,
      headers: message.headers,
    });

    return {
      messageId: info.messageId,
      accepted: (info.accepted ?? []).map(String),
      rejected: (info.rejected ?? []).map(String),
    };
  } finally {
    transport.close();
  }
}
